[package]
name = "movie-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
hyper = { version = "0.14.17", features = ["full"] }
serde_json = "1.0.107"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }