[package]
name = "movie-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] }
serde_json = "1.0.107"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
open = "5.0.0"
